package sftp

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDirectoryTracker(t *testing.T) {
	var updatedPath string
	tracker := NewDirectoryTracker(func(path string) {
		updatedPath = path
	})
	tracker.SetHomeDir("/home/testuser")

	// Sample OSC 7 sequence generated by bash / vte.sh
	oscSeq := []byte("some shell output\x1b]7;file://myhost/var/log/nginx\x07more output")
	tracker.FeedBytes(oscSeq)

	if updatedPath != "/var/log/nginx" {
		t.Fatalf("expected /var/log/nginx, got %s", updatedPath)
	}

	// URL encoded path
	oscSeq2 := []byte("\x1b]7;file://myhost/home/user/My%20Documents\x1b\\")
	tracker.FeedBytes(oscSeq2)

	if updatedPath != "/home/user/My Documents" {
		t.Fatalf("expected /home/user/My Documents, got %s", updatedPath)
	}

	// OSC 0 window title sequence (standard bash PS1)
	oscTitle := []byte("\x1b]0;user@host: /tmp\x07")
	tracker.FeedBytes(oscTitle)
	if updatedPath != "/tmp" {
		t.Fatalf("expected /tmp from OSC 0, got %s", updatedPath)
	}

	// OSC 0 with ~ expansion
	oscTitleTilde := []byte("\x1b]0;user@host: ~/projects\x07")
	tracker.FeedBytes(oscTitleTilde)
	if updatedPath != "/home/testuser/projects" {
		t.Fatalf("expected /home/testuser/projects, got %s", updatedPath)
	}
}

func TestLocalClient(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "pac_local_client_test")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	client := NewLocalClient(tmpDir)
	if !client.IsLocal() {
		t.Fatal("expected IsLocal() to be true")
	}

	// Test Mkdir
	newFolder := filepath.Join(tmpDir, "subfolder")
	if err := client.Mkdir(newFolder); err != nil {
		t.Fatalf("Mkdir failed: %v", err)
	}

	// Test ListDir
	items, err := client.ListDir(tmpDir)
	if err != nil {
		t.Fatalf("ListDir failed: %v", err)
	}
	if len(items) != 1 || items[0].Name != "subfolder" || !items[0].IsDir {
		t.Fatalf("unexpected items: %+v", items)
	}

	// Test Rename
	renamedFolder := filepath.Join(tmpDir, "renamed_folder")
	if err := client.Rename(newFolder, renamedFolder); err != nil {
		t.Fatalf("Rename failed: %v", err)
	}

	// Test Remove
	if err := client.Remove(renamedFolder); err != nil {
		t.Fatalf("Remove failed: %v", err)
	}
	itemsAfter, _ := client.ListDir(tmpDir)
	if len(itemsAfter) != 0 {
		t.Fatalf("expected 0 items after remove, got %d", len(itemsAfter))
	}
}
