package sftp

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDirectoryTracker(t *testing.T) {
	var updatedPath string
	tracker := NewDirectoryTracker(func(path string) {
		updatedPath = path
	})
	tracker.SetHomeDir("/home/testuser")

	// Sample OSC 7 sequence generated by bash / vte.sh
	oscSeq := []byte("some shell output\x1b]7;file://myhost/var/log/nginx\x07more output")
	tracker.FeedBytes(oscSeq)

	if updatedPath != "/var/log/nginx" {
		t.Fatalf("expected /var/log/nginx, got %s", updatedPath)
	}

	// URL encoded path
	oscSeq2 := []byte("\x1b]7;file://myhost/home/user/My%20Documents\x1b\\")
	tracker.FeedBytes(oscSeq2)

	if updatedPath != "/home/user/My Documents" {
		t.Fatalf("expected /home/user/My Documents, got %s", updatedPath)
	}

	// OSC 0 window title sequence (standard bash PS1)
	oscTitle := []byte("\x1b]0;user@host: /tmp\x07")
	tracker.FeedBytes(oscTitle)
	if updatedPath != "/tmp" {
		t.Fatalf("expected /tmp from OSC 0, got %s", updatedPath)
	}

	// OSC 0 with ~ expansion
	oscTitleTilde := []byte("\x1b]0;user@host: ~/projects\x07")
	tracker.FeedBytes(oscTitleTilde)
	if updatedPath != "/home/testuser/projects" {
		t.Fatalf("expected /home/testuser/projects, got %s", updatedPath)
	}

	// Windows cmd.exe prompt
	cmdPrompt := []byte("\r\nC:\\Windows\\System32>")
	tracker.FeedBytes(cmdPrompt)
	if updatedPath != "C:/Windows/System32" {
		t.Fatalf("expected C:/Windows/System32 from cmd.exe prompt, got %s", updatedPath)
	}

	// Windows PowerShell prompt
	psPrompt := []byte("\r\nPS C:\\Users\\tech\\Downloads> ")
	tracker.FeedBytes(psPrompt)
	if updatedPath != "C:/Users/tech/Downloads" {
		t.Fatalf("expected C:/Users/tech/Downloads from PowerShell prompt, got %s", updatedPath)
	}

	// Windows ConPTY OSC 9;9
	osc99 := []byte("\x1b]9;9;\"C:\\projects\\pac\"\x07")
	tracker.FeedBytes(osc99)
	if updatedPath != "C:/projects/pac" {
		t.Fatalf("expected C:/projects/pac from OSC 9;9, got %s", updatedPath)
	}

	// Windows OSC 0 title
	winTitle := []byte("\x1b]0;Administrator: C:\\Users\\Administrator\x07")
	tracker.FeedBytes(winTitle)
	if updatedPath != "C:/Users/Administrator" {
		t.Fatalf("expected C:/Users/Administrator from OSC 0 title, got %s", updatedPath)
	}

	// Windows OSC 7 with file:///C:/Users/tech
	winOsc7 := []byte("\x1b]7;file:///C:/Users/tech\x07")
	tracker.FeedBytes(winOsc7)
	if updatedPath != "C:/Users/tech" {
		t.Fatalf("expected C:/Users/tech from OSC 7, got %s", updatedPath)
	}
}

func TestLocalClient(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "pac_local_client_test")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	client := NewLocalClient(tmpDir)
	if !client.IsLocal() {
		t.Fatal("expected IsLocal() to be true")
	}

	// Test Mkdir
	newFolder := filepath.Join(tmpDir, "subfolder")
	if err := client.Mkdir(newFolder); err != nil {
		t.Fatalf("Mkdir failed: %v", err)
	}

	// Test ListDir
	items, err := client.ListDir(tmpDir)
	if err != nil {
		t.Fatalf("ListDir failed: %v", err)
	}
	if len(items) != 1 || items[0].Name != "subfolder" || !items[0].IsDir {
		t.Fatalf("unexpected items: %+v", items)
	}

	// Test Rename
	renamedFolder := filepath.Join(tmpDir, "renamed_folder")
	if err := client.Rename(newFolder, renamedFolder); err != nil {
		t.Fatalf("Rename failed: %v", err)
	}

	// Test Remove
	if err := client.Remove(renamedFolder); err != nil {
		t.Fatalf("Remove failed: %v", err)
	}
	itemsAfter, _ := client.ListDir(tmpDir)
	if len(itemsAfter) != 0 {
		t.Fatalf("expected 0 items after remove, got %d", len(itemsAfter))
	}
}
