package sftp

import (
	"testing"
)

func TestDirectoryTracker(t *testing.T) {
	var updatedPath string
	tracker := NewDirectoryTracker(func(path string) {
		updatedPath = path
	})

	// Sample OSC 7 sequence generated by bash / vte.sh
	oscSeq := []byte("some shell output\x1b]7;file://myhost/var/log/nginx\x07more output")
	tracker.FeedBytes(oscSeq)

	if updatedPath != "/var/log/nginx" {
		t.Fatalf("expected /var/log/nginx, got %s", updatedPath)
	}

	// URL encoded path
	oscSeq2 := []byte("\x1b]7;file://myhost/home/user/My%20Documents\x1b\\")
	tracker.FeedBytes(oscSeq2)

	if updatedPath != "/home/user/My Documents" {
		t.Fatalf("expected /home/user/My Documents, got %s", updatedPath)
	}
}
